### ISSUE TITLE
Chile

### ISSUE THREAD

**Issue by gabycosta04** [pdepmartestm/presentacion-GuidoDipietro#3]
Hola, me gustaria saber que opinas de Chile y si es un lugar interesante para vacacionar

**Comment by GuidoDipietro** [comment]
Hola, Chile es un gran país y muy lindo para conocer. La ciudad costera de Valparaíso es un lugar muy pintoresco e interesante ciudad para conocer, por ejemplo. La variedad de paisajes en Chile es similar a la de Argentina, sin embargo, pero la cultura es muy diferente.
